apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cfwx602n3-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cfwx602n3-nodejs 
  name: cfwx602n3-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cfwx602n3-nodejs 
